### PR TITLE
Update demo instructions in the readme

### PR DESCRIPTION
**Pull request by ricsantos**
Wanted to give the module a try, so did a clone, installed ionic, tried to run it but received this error:
```
$ ionic emulate ios
The emulate command has been renamed. To find out more, run:

  ionic cordova emulate --help
```

I believe the solution is:
```
ionic cordova emulate ios
```

That would get the project running in a simulator. Append `--target="iPhone-X"` for the latest and greatest. 

NB: Once the app launched in the simulator, no ManUp alerts appeared. I am not sure if I got it running correctly.

### CODE REVIEW

**Comment by ricsantos** [comment]
cc @zbarbuto

**Comment by ricsantos** [comment]
Also, not sure what branch should be merging this pr into, no `develop`?

**Comment by zbarbuto** [comment]
This is correct - ionic changed their api a while ago to namespace `cordova` commands.

**Comment by zbarbuto** [comment]
`master` is fine -`master` is what gets published to `npm`

**Review by zbarbuto — APPROVED** [review]
Failures are due to a recent update to ionic that is breaking everything. Happy to merge

**Comment by zbarbuto** [comment]
Ah should have picked up as well before merging - the `plugin` commands are also namespaced to `ionic cordova plugin <cmd>` - would you mind making another PR for those as well?

**Pull request merged**
