### PR TITLE
upgrade this plugin to be used in ionic 4 with angular 8

### PR DESCRIPTION
**Pull request by Mohammad-shoman**
I made some changed on this plugin so now it can be used with ionic 4 applicaitons

### CODE REVIEW

**Comment by Mohammad-shoman** [comment]
The test failed due to some changes that require for ionic 4 and angular 8 so please just fix the test classes so the tests pass

**Comment by zbarbuto** [comment]
Thanks for the contribution - I will take a look at the tests.

**Comment by zbarbuto** [comment]
@Mohammad-shoman Can you please allow contributions from maintainers so I can push the test fixes to your branch.

**Comment by Mohammad-shoman** [comment]
it's already allowed

**Comment by zbarbuto** [comment]
My mistake - I was trying to push to wrong branch 🤦‍♂

**Comment by zbarbuto** [comment]
Merged - thanks again.

Will be released as `1.0.0`

**Comment by Mohammad-shoman** [comment]
Thank you !

**Pull request merged**
